version: "3.7"
services:
  wolf-sheep-rabbit-client:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: wolf-sheep-rabbit-client
    restart: on-failure
    depends_on:
      - wolf-sheep-rabbit-server
    expose:
      - 80
    ports:
      - "80:80"
  wolf-sheep-rabbit-server:
    restart: on-failure
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: wolf-sheep-rabbit-server
    env_file: ./server/.env
    depends_on:
      - wolf-sheep-rabbit-db
    
  wolf-sheep-rabbit-db:
    container_name: wolf-sheep-rabbit-db
    image: postgres:13.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/db_init.sql
    restart: always